# Generated by Django 3.0.8 on 2021-06-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('image', models.ImageField(default='default.jpg', upload_to='Profile_pics')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
